spring.application.name=AirBnb
spring.datasource.url=DATABASE-URL
spring.datasource.username=USERNAME
spring.datasource.password=PASSWORD
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=airbnb_schema
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
frontend.url= http://localhost:8081
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
jwt_secret = JWT-SECRET
stripe.secret.key = STRIPE-SECRET-KEY
strip.webhook.secret =  STRIPE-WEBHOOK-SECRET

spring.cloudinary.cloud.name = CLOUD-NAME
spring.cloudinary.api.key = CLOUD-API-KEY
spring.cloudinary.api.secret = CLOUD-API-SECRET
spring.jackson.default-property-inclusion=non_null
